matrix:
  include:
    - language: python
      python: 3.7
      script:
        - python version
        - python exhibit.py

    - language: node_js
      node_js: 10
      install:
        - npm install -g reveal-md
      script:
        - reveal-md slides.md --theme night --static _static

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
  git checkout --orphan gh-pages
  git rm -rf --cached .
  git add -f --ignore-errors gallery/ _static/
  git -c user.name='travis' -c user.email='travis' commit -m init
  git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
  fi
