language: python
dist: xenial
cache: pip

python:
  - "3.7"

install:
  - git clone https://github.com/hakimel/reveal.js.git

script:
  - python exhibit.py

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
  git checkout --orphan gh-pages
  git rm -rf --cached .
  git add -f --ignore-errors gallery reveal.js
  git -c user.name='travis' -c user.email='travis' commit -m init
  git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG gh-pages
  fi
